{{/*
=============================================================================
KUBERNETES RESOURCE: ServiceAccount
=============================================================================
Purpose: Provide pod identity for RBAC and external authentication
Condition: Always created (required resource)
Used by: Deployment pods for Kubernetes API access and workload identity

Features:
  - Enables RBAC via RoleBindings
  - Supports workload identity (AWS IRSA, GCP Workload Identity, Azure AAD Pod Identity)
  - Auto-mounts API credentials to pods (configurable)

Annotations:
  - eks.amazonaws.com/role-arn: AWS IAM role for IRSA
  - iam.gke.io/gcp-service-account: GCP service account binding
  - azure.workload.identity/client-id: Azure managed identity
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  {{/* ServiceAccount name - referenced by Deployment */}}
  name: {{ include "cw-service.serviceAccountName" . }}
  labels:
    {{- include "cw-service.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  {{/*
  ===================================================================
  ANNOTATIONS
  ===================================================================
  Cloud provider workload identity mappings
  Example (AWS): eks.amazonaws.com/role-arn: arn:aws:iam::123456:role/my-role
  Example (GCP): iam.gke.io/gcp-service-account: my-app@project.iam
  */}}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{/*
===================================================================
AUTO-MOUNT SERVICE ACCOUNT TOKEN
===================================================================
Controls whether Kubernetes API credentials are automatically mounted to pods
- true (default): Pods can access Kubernetes API
- false: Improved security for apps that don't need API access
*/}}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}

